<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Create</title>
  </head>
  <body>
    <input id="time_restriction" type="text"/>
    <input id="views_restriction" type="text"/>
    <textarea id="code_snippet"></textarea>
    <button id="send_snippet" type="submit" onclick="send()">Submit</button>
  </body>
</html>